[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "medmnist-fl"
version = "1.0.0"
description = ""
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.19.0",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.5.1",
    "torchvision==0.20.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Art"

[tool.flwr.app.components]
serverapp = "medmnist_fl.server_app:app"
clientapp = "medmnist_fl.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 20
fraction-fit = 1
local-epochs = 2

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
